version: 2.1
executors:
  docker-env:
    environment:
      IMAGE_NAME: dexter1a6/product-server
    docker:
      - image: cimg/openjdk:8.0


jobs:

    build-and-test:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the Docker image tag below to openjdk version of your application.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
      executor: docker-env

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
      steps:
        - checkout
        - run:
            name: Maven build
            command: mvn -B -DskipTests clean package
        - run:
            name: Test
            command: mvn test

    docker-build:

      executor: docker-env
      working_directory: /home/circleci/project/docker-product-server/

      steps:
        - checkout
        - setup_remote_docker
        - run: echo "hello world"
        - run: ls
        - run:
            name: Build Docker image
            command: docker build -f Dockerfile -t $IMAGE_NAME:latest .
        - run:
            name: Archive Docker image
            command: docker save -o image.tar $IMAGE_NAME
        - persist_to_workspace:
            root: .
            paths:
              - ./image.tar


    publish-latest:

      executor: docker-env

      steps:
        - attach_workspace:
            at: /tmp/workspace
        - setup_remote_docker
        - run: echo "publish"
        - run: ls
        - run:
            name: Load archived Docker image
            command: docker load -i /tmp/workspace/image.tar
        - run:
            name: Publish Docker Image to Docker Hub
            command: |
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push dexter1a6/product-server:latest


workflows:
  version: 2.1
  build-master:
    jobs:

      - build-and-test:
          filters:
            branches:
              only: 
                - /release.*/

      - docker-build:
          requires:
            - build-and-test
          filters:
            branches:
              only: 
                - /release.*/

      - publish-latest:
          requires:
            - docker-build
          filters:
            branches:
              only: 
                - /release.*/